version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: develop.Dockerfile
    container_name: reactjs-transform-web
    volumes: 
      - ".:/app"
    env_file:
      - .env
    ports:
      - "3001:3000"
    tty: true